config/routes.rb
AlecServer::Application.routes.draw do
  
  root :to => 'pages#root'
  match '/about', :to => 'pages#about'
  match '/projects', :to => 'pages#projects'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController  

  def root
  end

  def about
  end
  
  def projects
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/application/_carousel.html.haml
- items ||= []
- id ||= 'myCarousel'
.carousel{:id => id}
  <!-- Carousel items -->
  .carousel-inner
    - items.each_with_index do |item, i|
      - if i == 0
        .active.item= image_tag item
      - else
        .item= image_tag item 
  <!-- Carousel nav -->
  <a class="carousel-control left" href="##{id}" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="##{id}" data-slide="next">&rsaquo;</a>

app/views/layouts/_header.html.haml
.container
  .navbar
    .pull-right
      %ul.nav
        %li= link_to 'Home', root_path
        %li= link_to 'Projects', projects_path
        %li= link_to 'Resume', '/Alec Hoey Resume.pdf'

app/views/layouts/_javascript_includes.html.haml
= render 'layouts/javascript_includes/google_analytics'

app/views/layouts/_sidebar.html.haml
.sidebar-nav
  .page-header
    %h1 Alec Hoey
  %ul.nav.nav-list
    %li
      %h2= link_to "about me", about_path
    %li
      %h2= link_to "about my projects", projects_path

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title
      Alec Hoey
      = content_for?(:title) ? "| #{yield(:title)}" : ''
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

  %body
    = render 'layouts/header'
    = yield

    .container
      %footer
        %p &copy; Alec Hoey

    = javascript_include_tag "application"
    = render 'layouts/javascript_includes'


app/views/layouts/javascript_includes/_google_analytics.html.haml
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-29847874-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/pages/projects.html.haml
- content_for :title, 'Projects'

.container
  .content
    .row
      .span4
        .well
          %h2 Google
          %p.flush-bottom= link_to 'http://offers.google.com/', 'http://offers.google.com'
          %p.flush-bottom Summer 2013
      .span8
        %h3.red Offers Ads Distribution Intern
        %ul
          %li Built a MapReduce pipeline to join large-scale and fragmented data sources using hybrid-hash joins and massive tables.
          %li Applied massively-scale ML techniques to train classification data on ad click conversions
          %li Developed an extensible library to allow flexible feature selection for experimentation
          %li Used model selection techniques to determine relevant feature sets and tuning parameters
        %p
          %strong The technologies:
          MapReduce, C++, proprietary Google tech

.container
  .content
    .row
      .span4
        .well
          %h2 Groupon
          %p.flush-bottom= link_to 'http://groupon.com/', 'http://groupon.com/'
          %p.flush-bottom Summer 2012
      .span8
        %h3.red Smartdeals/Relevance Intern
        %ul
          %li Developed a Hadoop parity pipeline to measure affected users by email ranking experiments
          %li Pipeline feedsback on experiements to give faster statistical significance theshholds  
        %p
          %strong The technologies:
          Hadoop, Java, Ruby
    .row
      .span4
        .well
          %h2 WSWE
          %p.flush-bottom= link_to 'http://whereshouldweeat.org/', 'http://whereshouldweeat.org/'
          %p.flush-bottom Spring 2012
      .span8
        %h3.red Personal Project
        %ul
          %li Complex multi-table polymorphic associations between different types of recommendations
          %li Loads of features: list, favorites, places, admin, chloropleth maps, etc.
          %li Experimented with recommender systems with Adobe Mahout
                  
        %p
          %strong The technologies:
          Ruby on Rails, Ruby, Postgres, APIs (JSON), Javascript, OAuth, RSpec
          
    .row
      .span4
        .well
          %h2 Magoosh
          %p.flush-bottom= link_to 'http://gre.magoosh.com/', 'http://gre.magoosh.com/'
          %p.flush-bottom Summer 2011 to Spring 2012
      .span8
        %h3.red Rails Developer Intern
        %ul
          %li Full-stack development from modeling to front-end jQuery calculator
          %li Learned the wonders of Agile development and modern software engineering
        
        %p
          %strong The technologies:
          Ruby on Rails, jQuery, Ruby, MySQL, HAML & SASS 
    
    .row
      .span4
        .well
          %h2 CalTeachables
          %p.flush-bottom Fall 2012
      .span8
        %h3.red Rails Developer
        %ul
          %li Developed lesson plan repository for local nonprofit with full-text search, admin approval system, and reviews
          %li Managed a team of 5 other developers with Agile as scrum master

        %p
          %strong The technologies:
          Ruby on Rails, Solr, jQuery

app/views/pages/root.html.haml
.container
  .content
    .row
      .span5
        .hero-unit
          %h1 Alec Hoey
          %h3 Software engineer
          %h4 machine learning specialist
          %h4 and web developer
      .span7
        %h2.tagline I believe in a web that empowers people
    
        %p
          My name is Alec. I'm a graduating senior at UC Berkeley majoring in Electrical Engineering and Computer Science.
          I'm a hacker at heart and learning and building cool things.
          Read about a few of my many projects
          = link_to 'here.', projects_path
      
        %p
          I specialize in machine learning, big data/data analytics, and web programming. I've done work ranging from implementing machine learning algorithms, feature selection, and parameter tuning to massive-scale MapReduce pipelines for data aggregation and analysis. I've also done extensive work with Ruby on Rails and the full web stack, modeling complex multi-table polymorphic associations all the way to front-end jQuery work.
      
.photo-banner
  .container
    = image_tag 'alec_albert_gerald.jpeg'
      
.container
  .content
    .row
      .span12
        %p
          Outside of work, I'm an active in
          = link_to 'Koinonia Christian Fellowship', 'http://www.koinonia.net/berkeley/k2/'
          and 
          = link_to 'Gracepoint Berkeley Church.', 'http://www.gracepointonline.org/'
          I also spend a lot of time reading, learning and practicing photography. Follow me on
          = link_to 'flickr.', 'http://www.flickr.com/photos/80479454@N05/'